spring:
  profiles:
    active: prod2

eureka:
  environment: prod
  datacenter: linux
  server:
    enable-self-preservation: true  # 关闭自我保护
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${zuihou.ip.local}:${zuihou.port.local}/eureka/
