# eureka 主机/端口配置 start
zuihou:
  ip:
    nginx: 127.0.0.1
    eureka: 127.0.0.1
    redis: 127.0.0.1
    rabbitmq: 127.0.0.1
    mysql: 127.0.0.1
    local: 127.0.0.1
  port:
    eureka: 8500
    nginx: ${server.port}
    local: 8505
  context-path:
    eureka: /zuihou-eureka
# eureka 主机/端口配置 end


server:
  port: ${zuihou.port.local}
  servlet:
    context-path:


eureka:
  instance:
    status-page-url: http://${zuihou.ip.nginx}:${zuihou.port.nginx}${server.servlet.context-path}${management.endpoints.web.base-path}/info
    status-page-url-path: ${server.servlet.context-path}${management.endpoints.web.base-path}/info
    health-check-url-path: ${server.servlet.context-path}${management.endpoints.web.base-path}/health
    preferIpAddress: true
    ip-address: ${zuihou.ip.local}
    instance-id: ${zuihou.ip.local}:${server.port}${server.servlet.context-path}
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    service-url:
#      defaultZone: http://admin:admin@127.0.0.1:8500/zuihou-eureka/eureka/
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${zuihou.ip.eureka}:${zuihou.port.eureka}${zuihou.context-path.eureka}/eureka/



logging:
  path: ./logs/zuihou-config
  file: ${logging.path}/root.log
  common-pattern: '%d{yyyy-MM-dd HH:mm:ss.SSS}:[%5p] [%t:%r] [%C{1}:%M:%L] --> %m%n'
  level:
    console: INFO

# 公共配置
spring:
  profiles:
    active: dev
  application:
    name: zuihou-config
  cloud:
    config:
      server:
        git:
#          uri: https://gitee.com/zuihou111/zuihou-admin-cloud
          uri: https://gitee.com/zuihou111/zuihou-admin-cloud-config-repo
          search-paths: zuihou-config-repo/*/{application}
  rabbitmq:
    host: zuihou.rabbitmq.host
    port: 5672
    password: guest
    username: guest
  security:
    user:
      name: admin
      password: admin
      roles: USER

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true

#management:
#  security:
#    enabled: true
#  context-path: /mgmt
#
#security:
#  basic:
#    enabled: true
#    path: ${management.context-path}
#  user:
#    name: admin
#    password: ${SECURITY_USER_PASSWORD:admin}
#endpoints:
#  health:
#    enabled: true
#    sensitive: true  # actuator的health接口是否需要安全保证

info:
  artifact: zuihou-config
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  spring-boot-version: '@spring.boot.version@'
  spring-cloud-version: '@spring.cloud.version@'