zuihou:
  port:
    nginx: 10086
  ip:
    redis: ${REDIS_HOST:192.168.1.2}
    rabbitmq: ${RABBIT_HOST:192.168.1.2}
    mysql: ${MYSQL_HOST:127.0.0.1}
    nginx: ${NGINX_HOST:127.0.0.1}
    eureka: ${EUREKA_HOST:127.0.0.1}
  mysql:
    msgs:
      database: zuihou_msgs_test      # 根据环境更改
    port: 3306                  # 根据环境更改
    username: root              # 根据环境更改
    password: bNVOqb7WKLX5Bjnw+LMv92taj25KOxDimXxILPQjw42wgv+1lHzOH8kr97xDwWdhpY67QuYCS7sWN4W46YbkFA==

spring:
  profiles:
    active: test