# eureka 主机/端口配置 start
zuihou:
  ip:
    nginx: 127.0.0.1
    eureka: 127.0.0.1
    redis: 127.0.0.1
    rabbitmq: 127.0.0.1
    mysql: 127.0.0.1
    local: 127.0.0.1
  port:
    eureka: 8500
    nginx: 9770  # 本地未开启nginx ，则nginx端口=zuul端口
    local: 9765
  context-path:
    eureka: /zuihou-eureka
    gate: /api
  mysql:
    admin:
      database: zuihou_admin_dev       # 根据环境更改
      driverClassName: ${zuihou.mysql.driverClassName}
      host: ${zuihou.mysql.host}
      password: ${zuihou.mysql.password}
      port: ${zuihou.mysql.port}
      url: jdbc:mysql://${zuihou.mysql.admin.host}:${zuihou.mysql.admin.port}/${zuihou.mysql.admin.database}?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false
      username: ${zuihou.mysql.username}
    driverClassName: com.mysql.cj.jdbc.Driver  # 6.0.6
    host: zuihou.mysql.host     # 根据环境更改
    port: 3306                  # 根据环境更改
    username: root              # 根据环境更改
    password: bNVOqb7WKLX5Bjnw+LMv92taj25KOxDimXxILPQjw42wgv+1lHzOH8kr97xDwWdhpY67QuYCS7sWN4W46YbkFA==
# eureka 主机/端口配置 end


logging:
  path: ./logs/${spring.application.name}
  file: ${logging.path}/root.log
  common-pattern: '%d{yyyy-MM-dd HH:mm:ss.SSS}:[%5p] [%t:%r] [%C{1}:%M:%L] --> %m%n'
  level:
    console: INFO
    rest: INFO
    service: INFO
    sql: DEBUG

server:
  port: ${zuihou.port.local}
#  servlet:
#    path: /
#    context-path:

eureka:
  instance:
    status-page-url: http://${zuihou.ip.nginx}:${zuihou.port.nginx}/api/admin/swagger-ui.html
    status-page-url-path: ${server.servlet.context-path:}${management.endpoints.web.base-path}/info
    health-check-url-path: ${server.servlet.context-path:}${management.endpoints.web.base-path}/health
    preferIpAddress: true
    ip-address: ${zuihou.ip.local}
    instance-id: ${zuihou.ip.local}:${server.port}${server.servlet.context-path:}
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    service-url:
       defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${zuihou.ip.eureka}:${zuihou.port.eureka}${zuihou.context-path.eureka}/eureka/

spring:
  profiles:
    active: dev
  application:
    name: zuihou-admin-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  rabbitmq:
    host: ${zuihou.ip.rabbitmq}
    port: 5672
    password: guest
    username: guest
  redis:
    host: ${zuihou.ip.redis}
    port: 6379
    key-prefix: dev
    jedis:
      pool:
        max-active: 20
        min-idle: 2
        max-idle: 8
#        max-wait:
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
  zipkin:
#    base-url: http://zuihou-zipkin:8510
    locator:
      discovery:
        enabled: true
    service:
      name: ${spring.application.name}
#    rabbitmq:
#      queue: zipkin
  security:
    user:
      name: admin
      password: admin
      roles: USER

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true

dozer:
  mappingFiles: classpath:dozer/global.dozer.xml

feign:
  hystrix:
    enabled: true

hystrix:
  config:
    stream:
      maxConcurrentConnections: 50
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000


swagger2:
  docket-info:
    admin:
      title: 权限管理服务
      description: 权限管理服务
      base-path: ${zuihou.context-path.gate}/admin
      modules:
        priAdmin:
          group-name: priAdmin
          packages: com.github.zuihou.admin.rest
  contact-name: zuihou
  contact-url: http://www.zuihou.com/
  contact-email: zuihou
  host: ${zuihou.ip.nginx}:${zuihou.port.nginx}



auth:
  serviceId: zuihou-auth-server
  app:
    token-header: token # 其三方应用token
    pub-key:
      path: app/pub.key
  client:
    id: zuihou-admin-server
    secret: 123456
    token-header: token
    admin-header: _isAdmin
    pub-key:
      path: client/pub.key

id-generator:
  machine-code: 1  # id生成器机器掩码


info:
  artifact: zuihou-admin-server
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  spring-boot-version: '@spring.boot.version@'
  spring-cloud-version: '@spring.cloud.version@'
